# Generated by Django 5.2.17 on 2026-08-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'Follow system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=16)),
                ('library_view', models.CharField(choices=[('list', 'List'), ('grid', 'Grid'), ('large', 'Large icons')], default='list', max_length=16)),
                ('reader_mode', models.CharField(choices=[('continuous', 'Continuous scroll'), ('single', 'Single page')], default='continuous', max_length=16)),
                ('reader_zoom', models.CharField(default='fit-width', max_length=16)),
                ('sidebar_open', models.BooleanField(default=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
