# Generated by Django 5.2.17 on 2026-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_quota_bytes',
            field=models.BigIntegerField(blank=True, help_text='Bytes this account may store. Blank uses the instance default; 0 means unlimited.', null=True),
        ),
    ]
