# Generated by Django 5.2.17 on 2026-08-18 03:55

import common.encryption
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_account_id', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('refresh_token', common.encryption.EncryptedTextField(blank=True)),
                ('scopes_granted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Authorization expired'), ('revoked', 'Revoked by user'), ('error', 'Error')], default='active', max_length=16)),
                ('status_detail', models.CharField(blank=True, max_length=512)),
                ('start_page_token', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriveRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_folder_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('original_path', models.CharField(blank=True, max_length=2048)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='google_drive.driveconnection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('partial', 'Completed with errors'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('discovered', models.PositiveIntegerField(default=0)),
                ('added', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('marked_missing', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('drive_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='google_drive.driveconnection')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='driveconnection',
            constraint=models.UniqueConstraint(fields=('user', 'provider_account_id'), name='unique_drive_account_per_user'),
        ),
        migrations.AddConstraint(
            model_name='driveroot',
            constraint=models.UniqueConstraint(fields=('drive_connection', 'provider_folder_id'), name='unique_root_per_connection'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['drive_connection', '-started_at'], name='google_driv_drive_c_c2a35f_idx'),
        ),
    ]
